name: trigger jenkins job
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: trigger single Job
      uses: johnnynaps/SpringDealership@automation-enhancements
      with:
        url: "http://localhost:8080/git/notifyCommit?url=https://github.com/johnnynaps/SpringDealership.git"
        user: "jnapoline"
        token: "11bfbb54c52ef7fa7e7657a16664ef583d"
        job: "Dealership"
